import {
  propertyAssessmentSchema,
  type ModelPropertyAssessment,
} from "@/lib/ai/prompts/analysis";
import {
  extractionOutputSchema,
  type ExtractionOutput,
} from "@/lib/ai/prompts/extraction";

/** Keys that only the server may set. A model must never be able to influence them. */
export const RESERVED_AUTHORITY_KEYS: ReadonlySet<string> = new Set([
  "payment_status",
  "state_version",
  "case_epoch",
  "active",
  "owner_id",
  "status",
]);

export function stripReserved(value: unknown, found: Set<string>): unknown {
  if (Array.isArray(value)) {
    return value.map((item) => stripReserved(item, found));
  }
  if (value !== null && typeof value === "object") {
    const clean: Record<string, unknown> = {};
    for (const [key, inner] of Object.entries(value)) {
      if (RESERVED_AUTHORITY_KEYS.has(key)) {
        found.add(key);
        continue;
      }
      clean[key] = stripReserved(inner, found);
    }
    return clean;
  }
  return value;
}

/**
 * Inspects raw text or raw JSON generated by the model before schema parsing.
 * Detects whether any reserved authority keys were emitted, logs a warning, and returns them.
 */
export function inspectRawModelOutput(rawTextOrJson: unknown): { foundReserved: string[] } {
  let parsed: unknown = rawTextOrJson;
  if (typeof rawTextOrJson === "string") {
    try {
      parsed = JSON.parse(rawTextOrJson);
    } catch {
      // not JSON or partial JSON
      return { foundReserved: [] };
    }
  }

  const found = new Set<string>();
  if (parsed !== null && typeof parsed === "object") {
    stripReserved(parsed, found);
  }

  if (found.size > 0) {
    const keys = Array.from(found);
    console.warn(
      `[security] Model output attempted to set reserved authority keys: ${keys.join(", ")}. Keys dropped.`
    );
    return { foundReserved: keys };
  }

  return { foundReserved: [] };
}

/**
 * Post-processes analysis model output: drops reserved authority keys (logging a
 * security warning), then enforces the assessment schema. Throws on schema violations.
 * If rawText is provided (or captured via onStepEnd), inspects it before Zod stripping.
 */
export function sanitizeModelOutput(
  rawOutput: unknown,
  rawText?: string
): ModelPropertyAssessment {
  if (rawText) {
    inspectRawModelOutput(rawText);
  }

  const found = new Set<string>();
  const stripped = stripReserved(rawOutput, found);

  if (found.size > 0) {
    console.warn(
      `[security] Model output attempted to set reserved authority keys: ${Array.from(found).join(", ")}. Keys dropped.`
    );
  }

  return propertyAssessmentSchema.parse(stripped);
}

/**
 * Post-processes extraction model output: drops reserved authority keys (logging a
 * security warning), then enforces the extraction schema. Throws on schema violations.
 */
export function sanitizeExtractionOutput(
  rawOutput: unknown,
  rawText?: string
): ExtractionOutput {
  if (rawText) {
    inspectRawModelOutput(rawText);
  }

  const found = new Set<string>();
  const stripped = stripReserved(rawOutput, found);

  if (found.size > 0) {
    console.warn(
      `[security] Extraction model output attempted to set reserved authority keys: ${Array.from(found).join(", ")}. Keys dropped.`
    );
  }

  return extractionOutputSchema.parse(stripped);
}
